### ISSUE TITLE
Showcase targeting input field, change position?

### ISSUE THREAD

**Issue by paulcanning** [amlcurran/ShowcaseView#269]
I have just started to implement Showcase, and I have it targeting an input field, but the circle centres itself on the field, whereas I'd prefer it to highlight the left hand side of the input field, where the placeholder text is,

Is this possible?

**Comment by mhyassin** [comment]
Is this fixed?

**Comment by amlcurran** [comment]
@mhyassin no, but I don't want to add this functionality into the library for two reasons:
- I want to avoid having specific view targets in the library (i.e. this is specific for EditText). This is because the more stuff is in the library, the more I have to maintain.
- This would be incredibly easy to implement yourself using a custom `Target`, simply duplicate the code for [`ViewTarget`](https://github.com/amlcurran/ShowcaseView/blob/master/library/src/main/java/com/github/amlcurran/showcaseview/targets/ViewTarget.java) and change the y position to use `view.getLeft()` instead of `view.getWidth() / 2`

**Comment by mhyassin** [comment]
@amlcurran I don't think that is specific for just EditText, I had the same problem for a LinearLayout, so I guess it's a general issue, on the other hand a custom target did the job for me :+1:
