### ISSUE TITLE
Fatal Exception: java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by Fornori** [amlcurran/ShowcaseView#371]
Fatal Exception: java.lang.IllegalArgumentException
width and height must be > 0
 raw
android.graphics.Bitmap.createBitmap (Bitmap.java:815)
android.graphics.Bitmap.createBitmap (Bitmap.java:761)
com.github.amlcurran.showcaseview.ShowcaseView.updateBitmap (ShowcaseView.java:211)
com.github.amlcurran.showcaseview.ShowcaseView.access$100 (ShowcaseView.java:51)
com.github.amlcurran.showcaseview.ShowcaseView$1.run (ShowcaseView.java:187)
android.os.Handler.handleCallback (Handler.java:808)
dalvik.system.NativeStart.main (NativeStart.java)

**Comment by Fornori** [comment]
Does any idea why? And how to prevent this?

**Comment by amlcurran** [comment]
Nope, I'll need some more information. Where are you using this, in an activity or a fragment? The more code you can post, the better

**Comment by zoopolitic** [comment]
this bug happens when you try to build and show showcase after closing activity, e.g. you have delayed showcase show, but user closes activity before showcase is shown, I've added isFinishing check but it didn't helped because in my case it returns false. Just try to delay show action and close activity.

**Comment by amlcurran** [comment]
thanks @zoopolitic that is really useful, I'm going to merge this issue into #197 as well and we'll track it in one place
